/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.inspira.polivoto.forms;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import org.inspira.polivoto.networking.AccionesDeCliente;
import org.inspira.polivoto.networking.IOHandler;
import org.inspira.polivoto.providers.LogProvider;
import org.inspira.polivoto.storage.InfoPapeleta;

/**
 *
 * @author jcapiz
 */
public class PapeletaDeParticipante extends javax.swing.JFrame
        implements ActionListener {

    private AccionesDeCliente accionesDeCliente;
    private String boleta;
    private String pregunta;
    private String perfil;
    private String actionCommand;
    private IOHandler ioHandler;

    /**
     * Creates new form PapeletaDeParticipante
     *
     * @param ioHandler
     * @param accionesDeCliente
     * @param boleta
     * @param tituloVotacion
     * @param perfil
     * @param info
     */
    public PapeletaDeParticipante(IOHandler ioHandler, AccionesDeCliente accionesDeCliente, String tituloVotacion, String boleta, InfoPapeleta info, String perfil) {
        this.ioHandler = ioHandler;
        this.accionesDeCliente = accionesDeCliente;
        this.boleta = boleta;
        pregunta = info.getTitulo();
        this.perfil = perfil;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setUndecorated(true);
        initComponents();
        setSize(screenSize);
        Dimension scaledSS = new Dimension();
        scaledSS.setSize(screenSize.getWidth()/3, screenSize.getHeight());
        jPanel1.setSize(screenSize);
        jLabel1.setText(tituloVotacion);
        jLabel2.setText(info.getTitulo());
        jLabel2.setBorder(BorderFactory.createEmptyBorder(1, (int)scaledSS.getWidth(), 1, 1));
        jLabel2.setSize(scaledSS);
        jLabel3.setText(boleta);
        jLabel3.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, (int)scaledSS.getWidth()));
        jPanel4.setLayout(new GridLayout(info.getOpciones().length, 1, 1, 10));
        JRadioButton rb;
        for (String opcion : info.getOpciones()) {
            rb = new JRadioButton(opcion);
            rb.setActionCommand(opcion);
            rb.addActionListener(this);
            buttonGroup1.add(rb);
            jPanel4.add(rb);
        }
    }

    @Override
    public void actionPerformed(ActionEvent evt) {
        actionCommand = evt.getActionCommand();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("PoliVoto Electrónico");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 1, 1, 1));
        jPanel2.setForeground(java.awt.Color.white);
        jPanel2.setLayout(new java.awt.GridLayout(3, 1, 10, 1));

        jPanel5.setBackground(new java.awt.Color(181, 75, 254));
        jPanel5.setBorder(null);
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel5.add(jLabel1);

        jPanel2.add(jPanel5);

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.darkGray);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jPanel2.add(jLabel3);

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.darkGray);
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel2);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(java.awt.Color.white);
        jPanel6.setForeground(java.awt.Color.white);
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setBorder(null);

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
        jScrollPane1.setViewportView(jPanel4);

        jPanel6.add(jScrollPane1, new java.awt.GridBagConstraints());

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(java.awt.Color.white);
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 40, 20));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jButton1.setBackground(java.awt.Color.white);
        jButton1.setForeground(java.awt.Color.black);
        jButton1.setText("Confirmar");
        jButton1.setBorder(null);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPreferredSize(new java.awt.Dimension(77, 37));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int veredicto = accionesDeCliente.enviaVotoParticipante(pregunta, actionCommand, perfil);
        LogProvider.logMessage("Papeleta", "Veredicto: " + veredicto);
        if (veredicto == 1) {
            accionesDeCliente.enviaParticipanteContestoPregunta(boleta, pregunta);
            new Timer().schedule(new TimerTask() {
                @Override
                public void run() {
                    dispose();
                }
            }, 5000);
            try {
                ioHandler.writeInt(48);
                ioHandler.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, "Voto guardado.");
            dispose();
        } else {
            LogProvider.logMessage("reply", "Por favor vuelva a dar click después de algunos segundos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
